name: Web Build + Deployment to GitHub Pages

on:
  push:
    branches:
      - master  # Deploy on push to the master branch
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python Environment
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build the Web App
      run: |
        mkdir -p build/web
        cp -r mainapp/* build/web/

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Deploy to GitHub Pages 🚀
      uses: actions/deploy-pages@v4.0.5
      with:
        artifact_name: github-pages-artifact
